version: '2.4'
services:
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    container_name: shadow-tls
    restart: always
    network_mode: "host"
    environment:
      - MODE=
      - LISTEN=
      - SERVER=
      - TLS=
      - PASSWORD=

# Available environs:
# MODE: client or server
# LISTEN: local listen address with port
# SERVER: remote address with port
# TLS: domain name in sni for client mode(like xxx.com.cn)
#      shadow-tls server address with port for server mode(like xxx.com.cn:443)
# PASSWORD: shadow-tls password
# THREADS(optional): set threads number(recommend to leave it blank)
# DISABLE_NODELAY(optional): disable TCP_NODELAY(recommend to leave it blank)
